import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ['nextjs', 'javascript'],
  openGraph: {
    title: 'Criando primeiro projeto com nextjs',
    description: 'O texto que descreve o conteudo a ser mostrado no card',
    images: [
      {
        url: 'url',
        width: 800,
        height: 600,
        alt: 'Uma imagem aleátoria qualquer'
      }
    ],
    videos: [
      {
        url: 'url',
        width: 800,
        height: 600,
      }
    ],
    audio: [
      {
        url: 'url'
      }
    ],
    locale: 'pt-BR',
    type: 'website'
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      nocache: true
    }
  },
  authors: [{ name: 'igorfonseca05' }, { name: 'igorfondev' }, { name: 'igorfonseca' }],
  publisher: 'Igor Ribeiro da Fonseca',
  formatDetection: {

  },


};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
