###
GET http://localhost:3000/api/games
###

POST http://localhost:3000/api/games
Content-Type: application/json

{
    "name": "Super mario",
    "price": 84.65
}
###

PUT http://localhost:3000/api/games?index=1
Content-Type: application/json

{
    "name": "Super Mario"
}
###
###
DELETE http://localhost:3000/api/games?index=1
Content-Type: application/json
###