
import { InfosProps } from "@/utils/types"
import Image from "next/image";
import { Post } from "./components/Post/Post";
import { Suspense } from "react";

import Head from "next/head";
import Container from "./components/container/Container";
import Cards from "./components/cards/Cards";
import MainCards from "./components/MainCards/MainCards";

import { Search } from "lucide-react";


async function getRepo() {
  try {
    const data = await fetch('https://api.github.com/users/igorfonseca05/repos',
      {
        cache: 'force-cache',
        next: { revalidate: 3600 }
      })

    return data.json()
  } catch (error) {

  }
}


export default async function Home() {

  return (
    <>
      <Head>
        <title>Insight and Updates - Stack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen text-gray-800 font-sans"> {/* Fundo geral e texto */}

        {/* Conteúdo Principal com Container Max-Width */}
        <main className="max-w-[1400px] mx-auto md:px-5 lg:px-0"> {/* Ajuste a largura máxima conforme necessário */}

          {/* Hero Section */}
          <section className="text-center lg:min-h-110 pt-40 pb-20 bg-gray-50 border-b border-gray-200 mb-10">
            <h1 className="text-5xl font-extrabold text-gray-900 mb-4 leading-tight">Code Journal</h1>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Stay informed with the latest insights from industry leaders,
              expert commentary, and honest advice to navigate the business landscape.
            </p>
          </section>

          {/* Articles Section */}
          <Container>
            <section className="py-10">
              <div className="mb-8">
                <h2 className="text-4xl font-bold text-gray-900 mb-3">All Articles</h2>
                <p className="text-lg text-gray-600">Browse our latest articles.</p>
              </div>

              <div className="flex justify-center mb-10">
                <ul className="flex flex-wrap w-full gap-4 bg-white p-2 rounded-lg shadow-sm border border-gray-200 text-gray-700 text-sm">
                  <li className="flex-1 relative">
                    <form action="" className="relative">
                      <span className="absolute top-[20%] bottom-[50%] ml-2">{<Search size={20} />}</span>
                      <input type="text" placeholder="Buscar artigos" className="w-full pl-10 py-2 rounded-md" />
                    </form>
                  </li>
                  <li className="px-4 py-2 rounded-md bg-orange-500 text-white font-medium cursor-pointer">All Articles</li> {/* Categoria ativa */}
                  <li className="px-4 py-2 rounded-md hover:bg-gray-100 cursor-pointer">Product Updates</li>
                  <li className="px-4 py-2 rounded-md hover:bg-gray-100 cursor-pointer">Company</li>
                  <li className="px-4 py-2 rounded-md hover:bg-gray-100 cursor-pointer">Productivity</li>
                  <li className="px-4 py-2 rounded-md hover:bg-gray-100 cursor-pointer">Marketing</li>
                </ul>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {/* Article Card 1 (Large - 2 colunas) */}
                <MainCards />
                {/* Article Card 3 (Small) */}
                <Cards tag="marketing" title="How to create a extensive omnichannel experience in the buying journey." description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." />
                <Cards tag="marketing" title="How to create a extensive omnichannel experience in the buying journey." description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." />
                <Cards tag="marketing" title="How to create a extensive omnichannel experience in the buying journey." description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." />
                <Cards tag="marketing" title="How to create a extensive omnichannel experience in the buying journey." description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." />
                <Cards tag="marketing" title="How to create a extensive omnichannel experience in the buying journey." description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." />
                <Cards tag="marketing" title="How to create a extensive omnichannel experience in the buying journey." description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." />
              </div>

              <div className="text-center mt-10">
                <button className="bg-white text-gray-700 px-6 py-3 rounded-lg shadow-md border border-gray-300 hover:bg-gray-100 transition duration-200">View More</button>
              </div>
            </section>
          </Container>
        </main>

        {/* Newsletter Section */}
        <section className="bg-gray-900 text-white py-20 mt-20 text-center">
          <h2 className="text-4xl font-bold mb-4">Publication & Newsletter Template for Figma</h2>
          <p className="text-lg text-gray-300 max-w-2xl mx-auto mb-8">
            Understand your target audience, identify your unique angle, design your articles.
          </p>
          <div className="flex justify-center space-x-4">
            <button className="bg-orange-500 text-white px-8 py-4 rounded-lg text-lg font-semibold hover:bg-orange-600 transition duration-200">Explore</button>
            <a href="#" className="text-white border border-gray-600 px-8 py-4 rounded-lg text-lg hover:bg-gray-800 transition duration-200">Contact Us</a>
          </div>
        </section>

        {/* Footer */}
        <footer className="bg-gray-900 text-gray-300 py-16 px-10 border-t border-gray-800">
          <div className="max-w-[1280px] mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-10">
            <div className="lg:col-span-2">
              <div className="flex items-center text-xl font-bold text-white mb-4">
                <img src="/logo-stack.svg" alt="Stack Logo" className="h-7 mr-2" /> {/* Substitua pelo seu logo */}
                <span>Stack</span>
              </div>
              <p className="text-sm mb-6 max-w-sm">
                Stack is a professional publication & newsletter template for Figma. With its clear structure and extensive features, Stack is a publication of any kind.
              </p>
              <div className="flex items-center text-sm border border-gray-700 rounded-md px-3 py-2 w-32 justify-between cursor-pointer hover:bg-gray-800">
                <span>English</span>
                <span>&#9660;</span> {/* Ícone de seta para baixo */}
              </div>
            </div>

            <div>
              <h4 className="text-white font-semibold text-lg mb-5">Products</h4>
              <ul className="space-y-3 text-sm">
                <li><a href="#" className="hover:text-white">Pricing</a></li>
                <li><a href="#" className="hover:text-white">Download</a></li>
                <li><a href="#" className="hover:text-white">Enterprise</a></li>
                <li><a href="#" className="hover:text-white">Referral</a></li>
              </ul>
            </div>

            <div>
              <h4 className="text-white font-semibold text-lg mb-5">Resources</h4>
              <ul className="space-y-3 text-sm">
                <li><a href="#" className="hover:text-white">Blog</a></li>
                <li><a href="#" className="hover:text-white">Help Center</a></li>
                <li><a href="#" className="hover:text-white">Documentation</a></li>
                <li><a href="#" className="hover:text-white">Press</a></li>
              </ul>
            </div>

            <div>
              <h4 className="text-white font-semibold text-lg mb-5">Social Media</h4>
              <ul className="space-y-3 text-sm">
                <li><a href="#" className="hover:text-white">LinkedIn</a></li>
                <li><a href="#" className="hover:text-white">Instagram</a></li>
                <li><a href="#" className="hover:text-white">Twitter</a></li>
                <li><a href="#" className="hover:text-white">Facebook</a></li>
              </ul>
            </div>
          </div>

          <div className="max-w-[1280px] mx-auto border-t border-gray-800 pt-8 mt-12 flex flex-col md:flex-row justify-between items-center text-sm text-gray-500">
            <p className="mb-4 md:mb-0">© 2024 Stack. All right reserved.</p>
            <div className="flex items-center space-x-2">
              <span>Made by</span>
              <img src="/webflow-logo.svg" alt="Webflow Logo" className="h-5" /> {/* Substitua pelo seu logo Webflow se usar */}
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}
