import Head from "next/head";
import Image from "next/image";

import style from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Meu project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
    
      <h1>Bem vindo ao meu primeiro projeto nextJs</h1>
     
     
    </>
  );
}
